name: Snake Animation
on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        
      - name: Generate Snake
        uses: Platane/snk@v3
        with:
          github_user_name: JamalDrakeAman
          outputs: output/snake.svg
        
      - name: Push Changes
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add output/snake.svg
          git commit -m "Update snake animation"
          git push
