name: Snake Animation
on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:
  push:
    branches: [main]

jobs:
  generate:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Generate Snake
        uses: Platane/snk@v3
        with:
          github_user_name: JamalDrakeAman
          outputs: |
            output/snake.svg
            output/snake-dark.svg?palette=github-dark
            output/snake-dark-2.svg?palette=github-dark-dimmed

      - name: Commit and Push
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add output/
          git commit -m "Update snake animations [skip ci]" || echo "No changes to commit"
          git push
